version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecommerce
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
